### ISSUE TITLE
(Peer review) Handle date selection 

### ISSUE THREAD

**Issue by Invictus17** [airavata-courses/VignyaanDwaarNirman#11]
Hi team,  
Great meeting you to discuss your project and conduct my peer review. I would like to highlight the following issues for your project:
1) Handling date in UI dashboard page.  
steps to recreate:
Naviagate to home page  
Go to Dashboard -> click on start date -> select a date  
Output:  
System breaks for this scenario.

**Comment by AnshulV98** [comment]
Ok, will look into it

**Comment by ghost** [comment]
Thank you for the feedback. This issue has now been resolved. You can select the date onClick
