### ISSUE TITLE
[Peer Review] Review Overview

### ISSUE THREAD

**Issue by gouthamgopal** [airavata-courses/VignyaanDwaarNirman#15]
Hey Team,

Thanks for the walk through of the whole architecture and helping in setup of the project.
It is a very clear and well executed architecture laid down to the simplest form for easy understanding.

The whole look and feel of the project is also great!
However I found some minor bugs which can be quickly sorted out. Will be raising them as different issues.

Please revert back with me if you need more clarification.

**Comment by devanshjain14** [comment]
@gouthamgopal 

Thank you for your feedback. 

It would be great if you could raise all those issues in the Issue section of our repository and our team will take care of them from thereon.

**Comment by ghost** [comment]
We have tried to resolve all the issues posted by  @gouthamgopal .
Please create a new issue, if you face a new one.
