### ISSUE TITLE
[Peer Review] Handling pyART dependencies

### ISSUE THREAD

**Issue by gouthamgopal** [airavata-courses/VignyaanDwaarNirman#16]
While setting up the project locally, I found out that setting up all the dependencies and utils for running pyART locally is highly complex and not a click-button installation.

Please try and come up with solutions as to how we can do it easily irrespective of the user environment.

**Comment by devanshjain14** [comment]
Hi, I forgot to mention in the README file that you must have anaconda env (with env variables set properly) and the python version must be 3.8+. 

And in case you are getting an IOError Unknown Compression Record, please change the contents of the pyart/nexrad_level2.py file with this, 
https://github.com/ARM-DOE/pyart/blob/master/pyart/io/nexrad_level2.py

Please let me know if you have any more issues with the same.

**Comment by gouthamgopal** [comment]
Okay. This seems like a quick enough solution. Closing the issue.
