### ISSUE TITLE
No information about fetching results

### ISSUE THREAD

**Issue by nayeembaig** [airavata-courses/VignyaanDwaarNirman#23]
![FetchResults](https://user-images.githubusercontent.com/17874908/77214370-38ba2600-6ae5-11ea-97b3-6422f4159486.JPG)

**Comment by AnshulV98** [comment]
The user has to stay at the dashboard for seeing the results, thats why we added a loading animation as well, although we should have mentioned it somewhere that generating the images and displaying it takes up a considerable amount of time. Thanks for pointing this out
