### ISSUE TITLE
Downtime in system 

### ISSUE THREAD

**Issue by tanvithote** [airavata-courses/VignyaanDwaarNirman#26]
I tried deleting the frontend pod.
The pod got deleted however, it took some time for new pod to start.
During this downtime, the application became unresponsive.
This problem is because there is only one replica of each pod.
I tried scaling the frontend deployment to 2 replicas using command - 
kubectl scale deployment/frontend --replicas=2
After scaling the deployment I tried deleting one frontend pod. This time the system had no downtime.

**Comment by AnshulV98** [comment]
Ok thanks for pointing this out and for the suggestion, will look into it and address this

**Comment by ViralPrajapati** [comment]
Actually we initially had 3 replicas for each micro-services but for jMeter testing we changed the configuration and forgot to get it back to original state. Still thanks for pointing this out I am reverting our system to 3 replicas. 
Commit hash: https://github.com/airavata-courses/VignyaanDwaarNirman/commit/200fa9934dceb42a02f99811933cfc727204e435

**Comment by ViralPrajapati** [comment]
The Config files have been updated
commit hash: https://github.com/airavata-courses/VignyaanDwaarNirman/commit/e649d26bc148b5c72a10b5da5f7134b4f1fa0c9e
