### ISSUE TITLE
Microservices Communication

### ISSUE THREAD

**Issue by AnshulV98** [airavata-courses/VignyaanDwaarNirman#3]
Learn microservices communication and implement a mock-architecture( consumer and producer)

**Comment by devanshjain14** [comment]
I have successfully run two microservices that are able to communicate with each other through amqp. #dedication

**Comment by ViralPrajapati** [comment]
I have created basic outline of 3 micro services i.e Data retrieval, Model execution and Analysis that are communicating with each other via rabbitmq as required and now will connect them to database. I think we should make separate database for each microservice, what do you guys think ?

**Comment by AnshulV98** [comment]
RabbitMQ has been integrated with the API gateway as well, now the gateway works as both a RestController and a message producer/consumer

**Comment by AnshulV98** [comment]
Going with RabbitMQ we have figured out, things can be improved, closing this issue, as newer issues will be created for future improvements
