### ISSUE TITLE
Istio static ip issue

### ISSUE THREAD

**Issue by ViralPrajapati** [airavata-courses/VignyaanDwaarNirman#34]
The installation and set up of Istio requires to make a ingress istio gateway to let external traffic interact with the system, but for this we need to expose our ip address to istio gateway. But for this when we try to follow the setup guide it is exposing the static ip address in place of floating ip address.  Hence, not being able to access the services from outside.

**Comment by AnshulV98** [comment]
After reading about this, I believe that the this would not work normally as Jetstream instances don't have external Load Balancers and hence, we cannot have an ingress gateway limiting us in many manners, hence, to overcome this nodeport is a possible solution

**Comment by AnshulV98** [comment]
For this to work, we need to change all the YAML files of Istio and changes their type from 'ClusterIP' to 'NodePort', though this is wrong, seeing the current situation this is the only viable option

**Comment by AnshulV98** [comment]
Ok, so once that is done, The automatic setup for the dashboards won't work, so we need a separate yaml file to install them, I think [this](https://github.com/DickChesterwood/istio-fleetman/tree/master/_course_files/warmup-exercise) will help

**Comment by AnshulV98** [comment]
This issue is resolved, hence closing this
