### ISSUE TITLE
Develop basic front-end 

### ISSUE THREAD

**Issue by AnshulV98** [airavata-courses/VignyaanDwaarNirman#5]
Developing a basic front-end for the web application

**Comment by devanshjain14** [comment]
Hi Anshul, 

I have developed the basic front end which gives a user the following functionality:

1. login using email password
2. register firstname lastname email password

Please let me know if there's anything more to be added

**Comment by AnshulV98** [comment]
Great Devansh, not anything at the moment, now that a basic UI has been implemented let's focus now on the development of backend microservices. If time permits we can have advanced login features and authorization features

**Comment by devanshjain14** [comment]
Please raise an issue to handle the incorrect password and already registered email id. I haven't handled it yet. I need to that.

**Comment by AnshulV98** [comment]
Kudos!! Closing this
