### ISSUE TITLE
User and Session Management

### ISSUE THREAD

**Issue by AnshulV98** [airavata-courses/VignyaanDwaarNirman#6]
Develop user and session management microservices

**Comment by devanshjain14** [comment]
I have completed the User management part. The only enhancement remaining in the social media sign up and log in.

**Comment by AnshulV98** [comment]
I think we can stow that part for now, for the next assignment

**Comment by ViralPrajapati** [comment]
I have completed Session management using node.js.

**Comment by AnshulV98** [comment]
Great work!! Closing this
